### ISSUE TITLE
Duration: 0?

### ISSUE THREAD

**Issue by thejamespower** [mkay581/scroll-js#16] opened 2017-06-22 11:46 UTC
Is there a way to instantly scroll, without an animation/transition? Currently have this:

```js
      scroll.toElement(element, { duration: 0 });
```

But doesn't seem to work. 👎

**Comment by mkay581** [comment] 2017-06-22 12:07
why not just change the [Element.scrollTop](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) property?

FWIW, the original goal of this package was to fill gaps in the spec in regards to scrolling elements--not necessarily to provide functionality that is already supported.

FYI, depending on the browsers you need to support, a lot of what this package does (i.e. `scroll()`, `scrollTo()`), are already [natively supported by evergreen browsers](https://drafts.csswg.org/cssom-view/#dom-window-scrollto). Animations are a part of that spec also.

**Comment by mkay581** [comment] 2017-06-22 12:10
After reviewing code though, it wouldn't hurt to implement a fix for this situation. Specifying a 0 duration should work. I'll submit a fix in a bit for it.

**Comment by thejamespower** [comment] 2017-06-23 11:35
We were using this library as a cross-browser solution, as we prefer to abstract non-standard (Internet Explorer) code out so it doesn't 'clutter' our code. We are using this library for across several UI components and it's all working well for us, was just a little stumped as to why zero duration didn't work. Thanks for the fix though.

**Comment by mkay581** [comment] 2017-06-23 12:00
Got ya, almost done with the fix. will open a pr and up the patch version once done. 👍

**Comment by mkay581** [comment] 2017-06-23 15:07
Hey @thejamespower opened a PR with the fix

**Comment by mkay581** [comment] 2017-06-23 21:32
Hey @thejamespower to clarify, there is really no fix for this because I tested passing duration:0 and it actually works. Not sure why it's not working for you. Do you mind pasting an example of your use case?

**Comment by mkay581** [comment] 2017-06-25 04:53
going to close this since I could not reproduce. if you're still having problems, feel free to comment in this thread.

**Closed by mkay581** 2017-06-25 04:53 UTC

**Comment by thejamespower** [comment] 2017-06-29 10:00
Thanks @mkay581, I'll investigate further our end.
