### ISSUE TITLE
Scrolling always starts at the top for Chrome and Firefox

### ISSUE THREAD

**Issue by mraerino** [mkay581/scroll-js#28] opened 2018-06-20 10:39 UTC
## Expected Behaviour

`Scroll.toElement` starts scrolling at current position

## Actual Behaviour

On Chrome and Firefox the scroll position is reset to the top and starts there.

## Usage

```
const element = document.getElementById(id);
const scroll = new Scroll(document.body);
scroll.toElement(element)
```

## Details

This is most likely related to the weird fact that `document.body.scrollTop` is always `0` on Chrome and Firefox

## Hacky fix

This works for us:

```
const element = document.getElementById(id);
const scroll = new Scroll(document.documentElement.scrollTop > 0 ? document.documentElement : document.body);
scroll.toElement(element)
```

*Notice: I know this will use `document.body` when the page is not scrolled. This prevents you from initializing the `scroll` object only once.*

----
This duplicates #25 - sorry

**Comment by mkay581** [comment] 2018-06-20 14:16
thanks, yeah. Its related to the browser inconsistency as mentioned in #25. Would you mind opening a PR for the change? :smiley:

**Comment by mraerino** [comment] 2018-06-20 15:40
I haven't really dug into the library details yet, but may probably find some time next week.
You seem to be handling the differences between `document.body` and `document.documentElement` already, but there seems to be some race-condition

**Comment by mkay581** [comment] 2018-06-20 15:57
A race condition? Hmm.. it's hard to diagnose the problem without an example. The bug identified in  #25 was partially due to absolute positioning being used and the parent not having its overflow content scrollable in the css. Maybe you can send me an example of your code? I'm not able to reproduce using the [Scroll To Element example](https://rawgit.com/mkay581/scroll-js/master/examples/scroll-to-element.html) exposed by this package.

**Comment by mkay581** [comment] 2018-07-02 12:59
Going to close this for now. Feel free to reopen if you can verify this is a bug with the package.

**Closed by mkay581** 2018-07-02 12:59 UTC
