### ISSUE TITLE
scrollIntoView not working in IE

### ISSUE THREAD

**Issue by chris-nc** [mkay581/scroll-js#55] opened 2019-10-11 18:36 UTC
I'm not able to get this working in IE. I'm getting this error:

SCRIPT5007: Object expected

It looks like IE is still expecting domElement.scrollIntoView instead of scrollIntoView(domElement...

**Comment by mkay581** [comment] 2019-10-19 15:01
Hello! Can you clarify? Not quite sure what you mean. How are you importing? Any steps to reproduce?

**Comment by chris-nc** [comment] 2019-10-22 15:44
I'm using IE 11.1387.16299.0
I'm using the scroller like this:
`
const boosterSection = document.querySelector('.stk-boosters');
scrollIntoView(boosterSection, { easing: 'ease-in-out', duration: 1000 });
`

It works as expected in Chrome, Safari, Firefox but in IE I get this error message:

`SCRIPT5007: Object expected`

I'm using the script in an Ember application and that error references this in our compiled JS:

` (0, _scrollJs.scrollIntoView)(boosterSection, { easing: 'ease-in-out', duration: 1000 });`

**Comment by mkay581** [comment] 2019-10-26 15:50
Hmm what version of scroll-js are you using? I've just made some IE11 updates in #56 that have been released in 3.1.0. And I'm able to get all examples working in IE11. Do you want to try the new 3.1.0 version?

**Comment by mkay581** [comment] 2019-10-26 21:18
Sorry didnt mean to close this

**Comment by mkay581** [comment] 2020-01-12 13:06
Going to close this due to inactivity. Please feel free to reopen if you are still experiencing issues. Thanks!

**Closed by mkay581** 2020-01-12 13:06 UTC
